SELECT
    B.BOOK_ID,
    DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE
FROM
    BOOK B
WHERE
    CATEGORY = '인문'
    AND DATE_FORMAT(B.PUBLISHED_DATE, '%Y') = 2021
ORDER BY
    B.PUBLISHED_DATE;